### ISSUE TITLE
Duplication of effort?

### ISSUE THREAD

**Issue by patcon** [JonnyBGod/grunt-push-release#10]
This looks really cool, but may I ask how it differs from grunt-release, a similar package with lots of users already?
https://github.com/geddski/grunt-release

Cheers! :)

**Comment by JonnyBGod** [comment]
It looks very similar and full of features.

Would need to check it a bit better but as for your question, by the time I started developing this modules I could not find any other that fitted my need.

Fill free to choose the one the better fit your needs.

Cheers.
