### ISSUE TITLE
pushing sub directory

### ISSUE THREAD

**Issue by sreevisakh** [JonnyBGod/grunt-push-release#12]
I have grunt task setup in project root folder. when I build my production ready code will be available in dist/ folder which is pointed to remote:production how can I push a sub directory using this plugin. a cwd option will be very helpful

**Comment by JonnyBGod** [comment]
This is not a regular use case and in my opinion not the best approach to what you are trying to do.

You can use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) or even better [git subtrees](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) for this.
