### ISSUE TITLE
Check for the current branch

### ISSUE THREAD

**Issue by asperling** [JonnyBGod/grunt-push-release#2]
It would be nice to only allow releases from a configurable branch or branches (most likely master). Chances are you're on a feature branch and forgot about merging.

**Comment by JonnyBGod** [comment]
Seam to me like a good feature.

Can you code it? I am very busy at the moment and will most likely not have the time for it for several weeks.

**Comment by asperling** [comment]
I did, see #4

**Comment by JonnyBGod** [comment]
Cool tks.

Seam to work fine.
